name: Deploy app
on:
  push:
    branches:
      ["main"]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          git clone https://github.com/praveenganeshcp/nodejs-pm2-poc
          cd nodejs-pm2-poc
          npm i
          pm2 start ./index.js
